#!/bin/bash

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║   AI PAPER TRADING - MANUAL STEP-BY-STEP INSTRUCTIONS         ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "🔧 COPY & PASTE THESE COMMANDS IN YOUR TERMINAL:"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  FIX DEPENDENCIES AND SETUP (Run ONCE):"
echo ""
echo "cd '/home/mayank/Desktop/AI Paper Trading'"
echo "bash COMPLETE_SETUP.sh"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""

echo "2️⃣  THEN CHOOSE ONE OF THESE OPTIONS:"
echo ""
echo "─────────────────────────────────────────────────────────────────"
echo "OPTION A: Run Everything at Once (Simplest)"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "bash run_simple.sh"
echo ""
echo "Then open: http://localhost:3000"
echo ""

echo "─────────────────────────────────────────────────────────────────"
echo "OPTION B: Run in Separate Terminals (Recommended for Development)"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 (BACKEND):"
echo "  cd backend"
echo "  bash run_backend.sh"
echo ""
echo "Terminal 2 (FRONTEND):"
echo "  cd frontend"
echo "  bash run_frontend.sh"
echo ""
echo "Terminal 3 (TESTING - optional):"
echo "  bash test_all.sh"
echo ""
echo "Then open: http://localhost:3000"
echo ""

echo "─────────────────────────────────────────────────────────────────"
echo "OPTION C: Manual Terminal Commands"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 (BACKEND):"
echo "  cd '/home/mayank/Desktop/AI Paper Trading'"
echo "  source backend/.venv/bin/activate"
echo "  export PYTHONPATH=\"/home/mayank/Desktop/AI Paper Trading:\$PYTHONPATH\""
echo "  python -m uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "Terminal 2 (FRONTEND):"
echo "  cd '/home/mayank/Desktop/AI Paper Trading/frontend'"
echo "  npm run dev"
echo ""
echo "Then open: http://localhost:3000"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ That's it! Your platform will be running."
echo ""
echo "📍 Access Points:"
echo "   • Frontend: http://localhost:3000"
echo "   • Backend: http://localhost:8000"
echo "   • API Docs: http://localhost:8000/docs"
echo ""
